### ISSUE TITLE
Include an organization key (nid or uuid) in the events API results

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#10]
@Nunie123 some of the students are working with the events API and something we discovered would make things a bit more flexible without adding endpoints is to provide a way to key between the organization and the event using.

The org endpoint returns a nid and a uuid.  Would it be possible to include either or both of those in the event API results?

@magoun @ThirtyThreeB

**Comment by Nunie123** [comment]
The nid and uuid are now returned with every event.

If it would be helpful, it is not complicated to add more endpoints.  If you think of something that will be useful, feel free to ask.  I'll let you know if it will be too much work to implement.

@allella @magoun @ThirtyThreeB

**Comment by allella** [comment]
Not necessary, but I did wonder if it would be helpful to call them
org_nid and org_uuid  just in case Eventbrite or Meetup has it's own uuid and confuses folks.
