### ISSUE TITLE
Confirm all REST API calls to the organizations API are defining _format=json

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#11]
@Nunie123 

I'm updating Drupal to the latest version due to recent major security releases and one of the side effects is the organizations API endpoints aren't going to automatically send JSON if no _format is set.

The simple solution is to make sure you have a [&_format=json](https://github.com/codeforgreenville/OpenData/issues/17) on the API endpoint query string. XML and HAL JSON are also possible, but I'm guessing most folks are going to use json.

I had _format documented, but my example endpoint URLs didn't show it as a required field since the REST service previously defaulted to JSON. It makes sense to require a format, but since it wasn't strictly noted I wanted to manually check with people using the API.

When Drupal 8 was in beta a couple years ago they also supported the Accept header but they [nixed it due to proxy and CDN support reasons](https://www.drupal.org/node/2501221).

**Comment by Nunie123** [comment]
@allella Thanks for the heads up.  Change has been committed and deployed.
