### ISSUE TITLE
Add Better Exception Handling

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#17]
In order to avoid fatal errors I had to catch some exceptions and ignore them.

These exist in 
format_meetup_events()
where we simply ignore using a "pass"
and
get_eventbrite_venues()
where the action is commented out

https://github.com/codeforgreenville/upstate_tech_cal_service/commit/0d37a9109f11de547a3cb98055373d559d0ab9e6

**Comment by allella** [comment]
@bcsnipes I think your pull request #19  fixed at least some of this issue.

I'm not good at debugging Python code yet so this was helpful to catch one of the issues that was giving us trouble.

Was the "None" value returned from Eventbrite something we can fix on our end? For instance, was it related to bad info in our organizations API?

**Comment by bcsnipes** [comment]
@allella I only found one event (at present) that was causing the error:

- 'Gadgetfest 9 Display Table', VenueID == None

This seems to be from an old event.
