### ISSUE TITLE
Apply Code Comments and Style Guide Recommendations As Needed

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#25]
[Style Guide](https://www.python.org/dev/peps/pep-0008/)

**Comment by ramonaspence** [comment]
I'm putting this on my to do list. It'll be another great learning experience :smile: +1

**Comment by allella** [comment]
API has been migrated to [Laravel PHP under the HackGreenville.com site](https://github.com/hackgvl/hackgreenville-com/pull/186), so closing this issue.
