### ISSUE TITLE
Meetup.com Events API Bot

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#3]
Ed already has a Meetup.com events bot.

[Cross-linking back to the open data API issue history](https://github.com/codeforgreenville/OpenData/issues/12) where the conversations started.

**Comment by allella** [comment]
@Nunie123 curious if the API is doing anything for deleted or changed events?

Asking because Code For Greenville has switched to the 4th and 1st Tuesdays but still seeing the original 3rd Tuesday event in the API and on the OpenWorks dashboard.
https://joinopenworks.com/dashboard/meetups.php

**Comment by Nunie123** [comment]
@allella The API should be updating every 5 minutes (and if an event is deleted from Meetup or Eventbrite it will stop showing up).  

The API has a "data_as_of" field, which indicates it was last updated on 3/27/18.  It's probably an issue with the cron job.  I probably forgot to make the python file executable last time I updated the code.  I should have time tomorrow to fix.

**Comment by allella** [comment]
@Nunie123 I was looking at conferences and noted that TEDx is using Eventbrite but not showing on the calendar. https://hackgreenville.com/calendar

The API key looks right
https://data.openupstate.org/organization/tedx-greenville

and they have an active event
https://www.eventbrite.com/o/tedxgreenville-2608611346

but don't see it in the events API
https://greenville-cal-service.herokuapp.com/api/gtc

Thoughts?

**Comment by allella** [comment]
@Nunie123 The Greenville Wordpress group also had a conference that didn't appear to show in the feed / calendar.

They post on Meetup.com
https://www.meetup.com/Greenville-South-Carolina-WordPress-Group/events/past/

I mentioned a similiar issue with TEDx + Eventbrite (above, sorry wrong thread).

Is it the case that conferences are somehow weeded out? Seems odd because the Greeville Wordpress group is marked as a Meetup Group and TEDX as a Conference in
https://data.openupstate.org/organizations

so seems like at least the Wordpress events should pull in like any other meetup event.

**Comment by allella** [comment]
We pretty well have a working Meetup bot and have other issues to fix or improve, so closing this issue.

**Comment by allella** [comment]
Example of pulling Code For Greenville's events.

https://api.meetup.com/Code-for-Greenville/events?&sign=true&photo-host=public
