### ISSUE TITLE
Eventbrite Not Showing Tech After Five Events

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#31]

**Comment by allella** [comment]
@ramonaspence I got on a roll and found the primary bug that was blocking Tech After 5's events from showing.

## Problem 1

As outlined in hackgvl/hackgreenville-com#217, the issue was that the API endpoint being called at Eventbrite is returning paginated results.

We were not filtering the results and Ta5 had over 550 past events. So, "page 1" of the API response results for Ta5 were the oldest 50 events, dating back to as early as 2010.

The filter_events_by_date method in app.py would purposely discard old events, which means it discarded ALL 50 of the Ta5 events, leaving no Ta5 events.

I've committed a fix to get around the old events / pagination-related issue. I'd do a pull request, but I haven't setup a proper dev environment or forked the project.  So, don't follow my lead and "do as I say, not as I do" :smile: regarding using a Github fork and pull requests.

## Problem 2
Now we have [two Tech After Five events showing in our events API](https://events.openupstate.org/api/gtc), but there are actually 7 scheduled in the future.

I believe the issue with the remaining 5 is related to them all being
`'venue_id': None,`
returned from Eventbrite's API.

I believe the get_eventbrite_venues() in app.py is filtering out events with no venue. If you can confirm if this is the case and propose a solution on dealing with "virtual" events, then we can discuss possible solutions on this issue.

## Problem 3
UPDATE: Solved by https://github.com/codeforgreenville/upstate_tech_cal_service/pull/33
For problem 1, I updated the API call to only pull events from the current time and later. 

In `filter_events_by_date()` the original developer, Ed, set our application to show events for the current date - 1 day.  The reason we did this was events would often roll off of calendars as they were happening. This as annoying because we'd have people show up confused looking for a meetup event and I'd look at OpenWorks' dashboard of what's happening that evening to ask them "are you looking for the Python meetup or Women Who Code".  Well, as soon as the event started they disappeared the next time the calendar refreshed.

I think this is as simple as subtracting 1 day from the 
`current_time = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')`
in
`get_eventbrite_events()`

Also, we'd want to rename that variable because current_time wouldn't make sense if we're subtracting 1 day from the value.

**Comment by ramonaspence** [comment]
@allella 

## Problem 2 ##

I'm looking at `get_evenbrite_venues` starting on line 153. 
On line 161 there is a check for `if venue_id is not None` but there seems to be no clause to execute for `if venue_id is None`.

Therefore I believe you are correct that events with "venue_id = None" are being filtered out somehow. 

I will fork this this afternoon and look more in depth to see if I can come up with a solution today. 

## Problem 3 ##

I think it would be good to have events stay on the calendar, perhaps for longer than a day. Maybe a 3-5 day week if that is suitable. Otherwise, I agree that that should be a solution.

**Comment by allella** [comment]
@pamelawoodbrowne @jeremywight @zach2825  you all have thoughts on if we keep events in our API for more than 1 day? We didn't want them to roll off immediately because of situations where the events would fall off a calendar immediately upon starting.

Ramona suggested going further, with keeping 3-5 days, and I'm fine with it.  I just wonder if we should keep as much as 31 days so the applications, like HackGreenville, can decide to show the previous month's events.

**Comment by allella** [comment]
@ramonaspence if you can address Problem 3 by moving the # of days into a config.ini variable which can be used throughout the script to adjust the # of days of history to retain.

This will remove the hard coded number and make it easy and flexible to make the change with just editing the config.ini.

We'll also want to put an example of that new variable in config.ini.example as a template.

Thanks for helping out.

Jim

**Comment by allella** [comment]
@ramonaspence we might rename the [past_events] past_days in config.example.ini so it matches the variable name in the app.

[past_events]
days_in_the_past

**Comment by allella** [comment]
@ramonaspence I was seeing if Eventbrite for today - 15 days would show more results and it doesn't for Tech After Five.  I realized that may still be related to the missing venue.

I was trying to test with -15 days and because Ta5's events were virtual they still didn't show up.

I ran it with -60 days and I can see stuff from Feb, so we should be good on the part, but Problem 2 is still in play, as you're aware.

However, if https://events.openupstate.org/api/gtc is called with no start_date in the URL, then it seems to not apply the -X days and returns only the current date.

I'm not familiar with Python or Flask's routing.  Is get_dates() being called when there are no dates provided in the URL?

I'm a bit confused right now because it seems like https://events.openupstate.org/api/gtc should default to the current date and then the -X days would be subtracted. However, it's only returning the current date and later.

**Comment by ramonaspence** [comment]
Alright, so we still have the issue of virtual events from eventbrite not being in the API, coming from an issue in get_eventbrite_venues.

And then the default (with no start_date) is not showing past events at all, where the default should be a start_date of 5 days ago. 

Just want to clarify I understand correctly. 

For ##Problem 2## 
The venue_id's for online events is = None, and because `get_eventbrite_venues` only has an `if venue_id is not None` clause. So nothing seems to be happening to the virtual events after this method. 

I believe if I add an If clause to handle the events where venue_id = None
And also handle these events in `format_eventbrite_events`
Then we will have all of the events coming in as expected (ie: virtual events, past events, etc)

The

**Comment by allella** [comment]
Sounds like a plan. Give it a go.

I suspect you're able to test this locally with your own API keys, but holler if you have any issues with that part.

**Comment by ramonaspence** [comment]
@allella 
> I'm not familiar with Python or Flask's routing. Is get_dates() being called when there are no dates provided in the URL?


I'm not quite familiar with Flask, however, from what I've been reading in their documentation I think I know what's going on with this. 

The get_dates() is tied to the url `/api/gtc`, in the sense that it gets called when the url is accessed. The three `request.args.get()` are looking for URL parameters, while the rest of this function grabs the events from the file "all_meetings.json" which is created in `update_cal_data.py`

So I should be able to specify the `days_in_the_past` variable for when start_date is not within the URL params.

**Comment by allella** [comment]
Thanks. I'm familiar with the args part and I assume now the _get__ is a pattern for an HTTP GET request.

What I don't understand is where is /api/gtc mapped to get_dates()?  I could see if it was implied by the name, but the name "dates" is not in the URL and I don't see a routes mapping like you usually see in frameworks.

Is it mapped to get_dates simply because it's directly below it and/or with no space between the route and the def?

**Comment by ramonaspence** [comment]
Yes, they're connected simply because get_dates() is directly under app.route()

https://flask.palletsprojects.com/en/1.1.x/quickstart/#routing

**Comment by allella** [comment]
I see the virtual events now.
https://events.openupstate.org/api/gtc

The default route doesn't show the past events, but I actually think that's not a bad thing as long as the event doesn't drop offer the default API endpoint as soon as it starts.

I'm closing this, but I want to start a new conversation about differentiating between the # of days in the past that available in the API vs the # of days returned by the default API route.

Nice work @ramonaspence .
