### ISSUE TITLE
Differentiate between Past Days Available and What's Returned by /api/gtc by Default

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#35]
@ramonaspence 

I'm thinking we should have two different date values.

1) the # of days in the past that available in the API pulls from Meetup and Eventbrite. This might be renaming the existing days_in_the_past to something like max_days_in_the_past_available.  We still want API requests to /api/gtc up to  current_date - max_days_in_the_past_available, but only  if the request explicitly asked for it using an earlier start date.

2) Then, we'd have a new  config value to set the # of days that /api/gtc returns when no start_date was passed as a GET query parameter.   This was previously 1 day and that may still make sense since we probably want the default API route to only return the current days events and what's in the future.  Maybe we call this default_days_in_the_past_returned

That make sense? What say ye?

**Comment by ramonaspence** [comment]
That makes sense. So we'll have a number of past_days that the api _shows by default_, and a number of past_days that are _available to be looked up_.

I'll look at it and then post back here with how I think it could best be implemented.


Edit: Okay that didn't take long.
It appears that I created that logic for the function `filter_events_by_date` but not inside of `get_dates`. 

This is why the default endpoint does not bring back the past events.
So the variable defined for default_days_in_the_past will go into the logic within `get_dates` while the variable defined for max_days_in_the_past will go into the logic within `filter_events_by_date`.

**Comment by ramonaspence** [comment]
In the function `filter_events_by_date` there is no reason to specify a start_date, correct?
This function is only called on when there are parameters given by the user via HackGreenville?

I must've gotten a little confused while I was setting that up yesterday, because I had the start_date on that function but not on `get_dates()`
