### ISSUE TITLE
Pull in Past Events from Meetup.com

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#37]
@ramonaspence it looks now like we have past Eventbrite events, but not past Meetup.com events in /api/gtc.

[Meetup's event docs for Request Parameters](https://www.meetup.com/meetup_api/docs/:urlname/events/#listparams) have a couple things we'll likely need to tweak.

I think it's only returning "upcoming" by default. 

We can do something like
`        url = 'https://api.meetup.com/{}/events?&sign=true&photo-host=public&status=upcoming,cancelled,past&page=20'.format(api)
`
but then it may return really old events and we don't want that. Returning old events might also cause an issue where we get paginated results for groups that have a lot of old results.

So, we probably want to use the no_earlier_than parameter to ask Meetup for events up to` max_days_in_the_past` days ago.

Then, I suspect /api/gtc will have up to `max_days_in_the_past` worth of events for both Meetup and Eventbrite.

At that point, we can test something like this request
https://events.openupstate.org/api/gtc?start_date=2020-04-01&end_date=2020-05-10
which is currently only returning Eventbrite results because we're not getting older Meetup.com events.

**Comment by allella** [comment]
Also, let's increase &page=20 to something like &page=50 so we don't have another situation where a group like Ta5 hosts a lot of events and we truncate results we want because we're not actively paginating through the results.  This is not foolproof because if an organization had over 50 events that we want to show in our API, then we'd really need to change the code to do proper handling of paged responses.

**Comment by allella** [comment]
We should also put a comment in the code above the Meetup.com API call to note it's set to only get the first 50 results. We have a note for this for Eventbrite.

At some point, an org like Ta5 is going to break our 50 event limit and it will help remind us that we're not paginating through results.

**Comment by ramonaspence** [comment]
Beginning on this, and so far so (relatively) good. 

## What I've done so far

The api call in app.py now looks like:

>   max_days_in_the_past = config.get('past_events', 'max_days_in_the_past')
>     current_time = datetime.datetime.utcnow()
>     no_earlier_than = (current_time - datetime.timedelta(int(max_days_in_the_past))).strftime('%Y-%m-%dT%H:%M:%S.000')
>     print('date', no_earlier_than)
> 
>     for api in group_apis:
>         # Create url from group name found in Organization API's field_event_api_key
>         url = 'https://api.meetup.com/{}/events?&sign=true&photo-host=public&no_earlier_than={}&status=upcoming,cancelled,past&page=50'.format(api, no_earlier_than)
> 
>         r = requests.get(url)
>         print(r.json())

This brings back events from May 9, 2020 through May 6 in 2021. Events with a status of Upcoming, Cancelled, or Past were all in the list.

**Comment by ramonaspence** [comment]
@allella Is there anything else I can do with this or would you say this issue has moved to hack-greenville?

**Comment by allella** [comment]
I think we're good. Thanks. Closing
