### ISSUE TITLE
Run Python tests and update test_fixtures.py

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#39]
The testing elements of the code haven't been used or updated in a long time and probably need to be checked.

I'm not Python guru, but this would seem to involve test_fixtures.py and tests.py

**Comment by ramonaspence** [comment]
@allella 
I will look at this tonight when I'm home from work.

I'm about to start learning to test via my Django project so this would be a great way for me to start learning.

**Comment by allella** [comment]
@ramonaspence Great. Let us know what you find.  Some simple edits to the docs would be good too so we have notes about how and when to run the tests.

**Comment by ramonaspence** [comment]
1. Compare test fixtures to objects returned by meetup and eventbrite APIs 
2. Name what each test tests for. Right now each testcase tests the format and thus the type of object returned by the method being tested. Is that all that needs to be tested? (probably not)
4. We know as of now the app works as expected with possible exceptions in edge-cases, so it should be safe to edit the tests for the descriptions that come from point 1, above. (ie: figure out correct expected result, test for expected results).

So since I'm still a bit new to testing I thought I would write out how I'm approaching this for the sake of writing documentation later and so that any of you can give feedback 

@allella

**Comment by allella** [comment]
@ramonaspence I'm new to it all as well. 

Since it's using the fixtures, I assume the initial intent was the test the code against valid-looking data and not test the code against the actual API.

Though, it seems we'd want to test a bit of both. That is, does the code work with a known example object. Plus, does the code work with a current example from the real APIs.

I'm not experienced with doing formal tests in any language so I don't know how much trying to validate or test remote APIs is considered to be in the scope.  Most testing examples I've seen seems to use stubbed out fake data as a known control against which to test the code for future regression.

If there's a good way to test a stable example fixture in one test, and then test a copy of a currently fetched data object from each real API, then perhaps that's an approach?

Again, I know less about testing and Python than you, so maybe we can see if anybody in the HG Python channel has suggestions.

**Comment by ramonaspence** [comment]
@allella I agree that there should be testing against static data as well as fetched data from the real APIs

Right now I'm updating the test fixtures. I'm running the app to see the individual return results from the functions, and can compare that to a manual call to that API to see if the test_fixture needs to be updated (also, checking what errors come up when running tests versus errors that come up when running the program).

So far two fixtures: `open_upstate_response_text` and `meetup_events_list_text` needed minor changes to reflect the data coming back.

**Comment by jdonboch** [comment]
sounds like the right direction, i'd be happy to review a WIP PR when it's ready or if you want early feedback

**Comment by allella** [comment]
API has been migrated to [Laravel PHP under the HackGreenville.com site](https://github.com/hackgvl/hackgreenville-com/pull/186) and the new implementation has testing, so closing this issue.

Thanks for those who contributed to this issue.
