### ISSUE TITLE
Broken Link in deploy_notes_initial.md

### ISSUE THREAD

**Issue by ramonaspence** [codeforgreenville/upstate_tech_cal_service#42]
In deploy_notes_initial.md, there is a link to creating an Eventbrite token. 

The link is taking me to Eventbrite's website, but the website returns a 404 for this page. 

I believe the current link in the deploy notes can be replaced by this link:
https://www.eventbrite.com/platform/api#/introduction/authentication/1.-get-a-private-token ,
which takes you to Eventbrite's documentation on authentication.

**Comment by ramonaspence** [comment]
While on this topic, do we need to add steps to deploy_notes_initial.md to show what data the AWS section of the config.ini is looking for?
The config.ini.example:
```[aws]
username = user
update_cal_location = /home/user/upstate_tech_cal_service/update_cal_data.py```

**Comment by allella** [comment]
@ramonaspence do you see where the AWS config is used?  It was added by Ed, the original dev, and he may have had it on AWS, but it's not something we're using on the production server, which isn't on AWS.

Eventbrite did change their API to a new version in recent years, so the new link would be good.

Thanks

**Comment by ramonaspence** [comment]
> 

Oops, my apologies. I thought I had already responded to this. 

I don't see anywhere that the AWS config is being used. My guess is that it was being tested on AWS? 

Since it's not used on the production server, I went ahead and removed it. 

The next PR that I make will have the updated link to Eventbrite's documentation on receiving a token.
