### ISSUE TITLE
Sorting of API Results

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#49]
@ramonaspence I'm not sure if this is a result of the API rework, or if I'm missing something.

I noticed events on the OpenWorks dashboard aren't in time order and I see the results in the API aren't, which is why.

I'm assuming this is related to the recent PR.  Do you think we were previously sorting the results by the event date?

https://events.openupstate.org/api/gtc

**Comment by ramonaspence** [comment]
Oh I see! Okay, I added a function to sort by time before it gets formatted for JSON or JSON+LD
I retested it in Postman, so I'll go ahead and create a pull request and let you review/re-test it.
