### ISSUE TITLE
Facebook.com Events API Bot

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#5]
There is currently no Facebook.com events API bot.

[Cross-linking back to the open data API issue history](https://github.com/codeforgreenville/OpenData/issues/10) where the conversations started.

**Comment by Nunie123** [comment]
My research on the facebook API revealed that API keys last, at most, for a month.  Facebook would like a user to log in every time it accesses the API.

Our options for getting events from facebook groups is:
1. Have someone manually request a new API key from facebook every month and then update the config file on the server to use the new key.
2. Implement a method for the server to give facebook credentials and generate a new API key on its own.  (there is no api for this, we'd probably have to do a headless browser and scraping, or something equally complicated)
3. Scrape the html off of facebook group pages and parse it. (it's possible this is a violation of facebook ToS)

Given the complexity of the possible solutions I could come up with, I'd prefer not to work on this issue unless there is a high user demand.

**Comment by allella** [comment]
Fine with me to not do anything complex for Facebook.

The only group using FB is FreeCodeCamp.  They meet every week at the same time so we can probably figure out a work around and/or have the group program a work-around for us.

@pamelawoodbrowne maybe we could bring Daniel Jones into the conversation? I don't know his GitHub handle.

**Comment by allella** [comment]
https://data.openupstate.org/organizations?city=greenville&org_status=active&event_service=facebook
