### ISSUE TITLE
Nvite.com Events API Bot

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#6]
There is currently no Nvite.com events API bot.

[Cross-linking back to the open data API issue history](https://github.com/codeforgreenville/OpenData/issues/32) where the conversations started.

**Comment by Nunie123** [comment]
Nvite does not have an API that can be used to access event data.  Web scraping appears to be the only option.

**Comment by Nunie123** [comment]
Nvite has been acquired by Eventbrite.  I'm unsure if these will continue as separate services.

http://fortune.com/2017/03/31/eventbrite-acquires-nvite/

**Comment by allella** [comment]
That works.

Technically a Coffee was the only meetup using Nvite, but they are now inactive so closing this unless/until we have an Nvite user.

https://data.openupstate.org/organizations?city=greenville&org_status=active&event_service=nvite
