### ISSUE TITLE
Docs: Add Notes About using Apache and Nginx gzip / Deflate Compression for Text Formats Like JSON and JSON+LD

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#61]
@ramonaspence this is indirectly related to the app, but it is something many developers don't learn until late in their careers, if every, since it's more of web server configuration than an app setting.

For basic text formats, like HTML, CSS, Javascript, XML, and JSON, the web browser typically sends a Request Header, like
_Accept-Encoding: gzip, deflate, br_, which is the browser's way of telling the web server it's capable of receiving a zipped / compressed file and then uncompressing it on the browser end.  The net savings is often drastic, like 8-10X smaller transfers. 

I should add that compression is the default in newer HTTP/2 and HTTP/3 protocols (and the now deprecated SPDY protocol).

While CDNs and most 3rd party hosts use H2 or H3, an out of the box Apache or Nginx can easily default to only supporting HTTP/1.1, and thus you'd not have gzip compression on a server unless it was explicitly enabled, or unless an H2 or H3 module is installed and enabled for the web server.

For instance, the [default Events API JSON response](https://events.openupstate.org/api/gtc) is currently 114.9 KB, but I enabled gzip compression in the Apache web server for this domain, hit refresh, and it now transfers the same response in 10.37 KB.

I did some consulting work last year for a company using Apache and with this trick I shaved about 80% of their homepage transfer size in 1 line in Apache configuration and a reload of the web service.

This doesn't work on images, videos, or other "binary" formats, since they are typically already compressed.  However, it is something that's often overlooked.  I even overlooked it on this API because of the added complexity of using gunicorn + Apache, but with a few minutes of work it is now enabled.

You can see the difference in "transferred size" vs "size" (uncompressed) in Firefox rather easily.  In this image, [with the tags=1 parameter in the URL](https://events.openupstate.org/api/gtc?tags=1), the actual data transferred over the network for the JSON was 3.19 KB instead of 12.8 KB
![image](https://user-images.githubusercontent.com/1777776/169439150-9e19be54-bc24-4a93-b934-b12700a4adc3.png)

You can also see this in [Postman API client](https://learning.postman.com/docs/getting-started/introduction/) by turning on / off the _Accept-Encoding: gzip, deflate, br_ in Postman's Request Headers tab (the Header tab at the top), reload the request, and then looking at the "Size" (in green text) of the response as it goes from 114.9 KB to 10.37 KB.

![image](https://user-images.githubusercontent.com/1777776/169439389-db2877c4-23b5-4d2e-9553-55d74eac33c5.png)

In Chromium browsers, you can see it too, but you have to mouse-over the "Size" value of the main request.

![image](https://user-images.githubusercontent.com/1777776/169441460-486ad397-1a17-44fc-a3b1-1ed7d37b5b84.png)

For Apache, the .htaccess or Apache domain config file needs something like the following, and then a daemon reload
`AddOutputFilterByType DEFLATE text/css text/html application/x-javascript application/javascript text/javascript application/json+ld application/json
`

[In Nginx, I believe the same gzip trick](https://docs.nginx.com/nginx/admin-guide/web-server/compression/) would be something like the following, and then a daemon reload.
```
gzip on;
gzip_types      text/css text/html application/x-javascript application/javascript text/javascript application/json+ld application/json;
```

Note, that I had to explicitly add our two more modern content types, `application/json+ld application/json` to the list of supported types.

In any case, you don't need to worry about this, but it's one of those things that is a best practice that's not typically enabled on the web servers by default, and therefore frequently never done.

**Comment by allella** [comment]
I should add that compression is the default in newer HTTP/2 and HTTP/3 protocols (and the now deprecated SPDY protocol). 

While CDNs and most 3rd party hosts use H2 or H3, an out of the box Apache or Nginx can easily default to only supporting HTTP 1.1, and thus you'd not have gzip compression on a server unless it was explicitly enabled, or unless an H2 or H3 module is installed and enabled for the web server.

**Comment by ramonaspence** [comment]
This is really cool! I'm glad you showed me this 😀
