### ISSUE TITLE
Differentiate virtual location from physical in JSON-LD

### ISSUE THREAD

**Issue by ramonaspence** [codeforgreenville/upstate_tech_cal_service#65]
Right now, for online events we have changed the `type` of the location property for online events to `virtualLocation` and we've added an URL property to the location.

```
"location": {
                    "@type": "VirtualLocation",
                    "url": "https://www.meetup.com/Code-for-Greenville/events/qwpbksydcjbkb/"
                }
```

A [question](https://github.com/codeforgreenville/upstate_tech_cal_service/pull/57#issuecomment-1132366984) on the topic of `virtualLocation`'s properties was raised in #57 by @allella, as to where the URL for a `virtualLocation` should link. To the event's homepage or directly to a stream?   

Schema.org [documentation](https://schema.org/VirtualLocation) doesn't specify this explicitly, but all examples I have found put "stream" in the mock URL. This can be seen on [Google](https://developers.google.com/search/docs/advanced/structured-data/event#online-event) and on [Schema.org](https://schema.org/VirtualLocation#eg-0014) (click on the JSON-LD tab of this example). However, we don't receive this link from Meetup or Eventbrite APIs by default. Maybe it's possible to explicitly request that URL if it's provided by the event itself? If we can't access it, should we still include the event's homepage under `virtualLocation` even though that link is already provided in the event? 

If a stream link is set by the organizer of an event ahead of time, where would this be shown? Could we use Code for Greenville's Meetup.com page to test whether it allows us to specify a stream link upon creating or updating the event?

**Comment by allella** [comment]
@ramonaspence regarding the stream URL, I set one for the [June 7th Code For Greenville event](https://www.meetup.com/Code-for-Greenville/events/285681435/) (event ID 285681435).  Though, the admin side does say it's only visible to those who RSVP, so it's unclear if it will show in the Meetup.com API
![image](https://user-images.githubusercontent.com/1777776/171540477-71766bac-14b9-4abb-9c22-ec9615136bec.png)

I don't see the video stream URL in [the raw API response](https://api.meetup.com/Code-for-Greenville/events?&sign=true&photo-host=public&no_earlier_than=2022-06-01T08:00:00.000&status=upcoming,cancelled,past&page=50).
![image](https://user-images.githubusercontent.com/1777776/171542669-9a4ddd90-74b4-4547-a1ba-6b4f2742e18e.png)

On wrinkle in all this is the [Meetup API docs now only show info for GraphQL](https://www.meetup.com/api/). Here's the [GraphQL response for an Event](https://www.meetup.com/api/schema/#Event).

There is a URL listed on the [OnlineVenue in the GraphQL](https://www.meetup.com/api/schema/#OnlineVenue), so perhaps the newer API has this info?

I don't see the older REST API documentation so if the video URL is part of some other REST API call to Meetup.com, then we'd need to fine it.

Also, it seems this GraphQL change may be writing on the wall that the REST API will be deprecated, or perhaps even turned into a "Pro" feature.

**Comment by allella** [comment]
Regarding the REST API, there is a JSON format of the docs at https://api.meetup.com/docs but I recall there was previously being an HTML set of docs.

A change to GraphQL would also involve using OAuth2 and probably the [JWT flow](https://www.meetup.com/api/authentication/#p04-jwt-flow-section) since we'd be building an app that isn't requesting other people to authorize access.

**Comment by ramonaspence** [comment]
@allella 

> Though, the admin side does say it's only visible to those who RSVP, so it's unclear if it will show in the Meetup.com API

My guess at this point is that the stream URL, if provided at all, requires an individual account that has RSVP'd to authenticate the API call. From what we've seen with the migration to GraphQL API that requires a premium account, we may have to shelve this. I haven't been able to find an URL that's specifically for the stream/group call.

**Comment by allella** [comment]
Yeah, I guess it's a privacy / security thing, so we're probably not going to get the link and perhaps that's a good thing so people don't bomb a meetup by not registering.

Closing. Thanks for entertaining it.
