### ISSUE TITLE
Add Schema org properties to JSON-LD output

### ISSUE THREAD

**Issue by ramonaspence** [codeforgreenville/upstate_tech_cal_service#66]
Since we're still learning about Schema org and linked data, there's still ways that we can enhance the JSON-LD output. This issue is not an exhaustive list of things to change, but a starting point. There are some Schema properties that we can add which are counterparts to fields our colloquial JSON format already has.

The first property that we can add to all events is the [eventAttendanceMode](https://schema.org/eventAttendanceMode) which indicates whether an event is online, offline, or a combination of both. There's also a property for an `Event`'s [status](https://schema.org/EventStatusType) that we may want to add. Both of these properties would be in the `Event` itself rather than the location. This can be seen in action in [Google's guidance](https://developers.google.com/search/docs/advanced/structured-data/event#online-event) as well as [Schema.org](https://schema.org/eventAttendanceMode#eg-0014).

Another property that I noticed was missing is an URL for the [organizer](https://schema.org/organizer) field. Implementing this will be different for Meetup and Eventbrite but very do-able. 

Again, this is just a starting point, so we can add to this issue as we go. 😃 👍

**Comment by allella** [comment]
Sounds good.  I posted related notes to https://github.com/codeforgreenville/upstate_tech_cal_service/issues/65#issuecomment-1144364950

**Comment by ramonaspence** [comment]
>Another property that I noticed was missing is an URL for the [organizer](https://schema.org/organizer) field. Implementing this will be different for Meetup and Eventbrite but very do-able.

This is just a small update and I'm continuing to figure this out. 

I'm looking at this again, and I don't think we have access to the organizer_id *and* the organization name, which are the two items that I would have used to construct the URL of the Eventbrite organizations. There is a `field_event_calendar_homepage` but for some events this is the event homepage and for others it's the organization's homepage. I'm not sure we would want that kind of inconsistency or if that would work for our purposes. 

I'll go ahead and create a PR for adding the eventAttendanceMode and eventStatus though.

**Comment by allella** [comment]
Would the homepage URL coming from the orgs API work? It's not going to be consistent, but if you're just linking off to a place to learn about the organization / organizer, then whatever we set in the homepage is probably better than nothing.  We can also update the orgs API, or even add more fields, but I wouldn't want to completely change the purpose of those existing fields or have more confusing URLs to maintain if we can't easily differentiate the purpose of the various URLs in the orgs API.

**Comment by ramonaspence** [comment]
I think that would work fine. Some of them might go to an Eventbrite or Meetup page, and some might go to the organization's website. But you're right, it would be better than not having the Organizer field at all.
