### ISSUE TITLE
Update Flask and Packages

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#71]
@ramonaspence I saw a Flask security update and it reminded me we could do more regular updates on the packages.

Are you still able to chip in on supporting this repo?

Thank,
Jim

**Comment by ramonaspence** [comment]
Hi! Sorry I've been gone for awhile, but I am going to try to keep supporting this repo. 

I've opened a pull request with an updated Pipfile.lock 👍
