### ISSUE TITLE
Rebranding / renaming the GitHub Organization and Possibly this Repo's Name

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#73]
@ramonaspence @oliviasculley since we've [changed the GitHub org from codeforgreenville or hackgvl](https://hackgreenville.slack.com/archives/C3XNGDEBT/p1686100597153389), it's useful to update our local Git configurations.

[GitHub provides some examples on updating a remote URL](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#changing-a-remote-repositorys-url) but I think editing .git/config in a local repo should also do the trick and is possibly easier.

![image](https://github.com/hackgvl/upstate_tech_cal_service/assets/1777776/5da01c94-5bea-4923-9017-08b404a107ca)

Additionally, I'd like to propose we rename this repo from _upstate_tech_cal_service_ to _events-api_

Also, if the https://github.com/hackgvl/eventsbot repo is only going to do things related to Slack, then it may avoid some confusion to include the word "slack" in that repo name, like slack-events-bot

Thoughts?

**Comment by oliviasculley** [comment]
This sounds good, I've renamed the eventsbot to [slack-events-bot](https://github.com/hackgvl/slack-events-bot), but I haven't renamed the docker image for it yet. Please let me know if you'd like me to rename that, since the `docker-compose.yml` on the hosted location will most likely need to change as well

**Comment by allella** [comment]
Yeah, I think it would be good to rename the Docker image too.

Since we're using mostly dashes for spaces in repo names, I think we can stick with that going forward so our repos don't look inconsistent like with the CFG ones did over time.

**Comment by allella** [comment]
@zach2825 just a general notes that we've renamed the GitHub org and even some of the repo names.

This repo is going to be renamed too.

**Comment by allella** [comment]
@ramonaspence @oliviasculley the Events API repo name is now https://github.com/hackgvl/events-api/

We should update our "upsteam" .git/config branch URls in our local cloned copies to the new URL path.

And, it may be good to rename our forks of this repo so they are /events-api too.
